/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace MRMLScene.Bridge.Services
{
  public enum KISResult
  {
    SUCCESS = 0,
    FAIL = -1,
    ERROR_PARAMETER = -2,
    ERROR_EXCEPTION = -3,
    ERROR_INVALIDDIR = -4,
    ERROR_FILENOEXIST = -5,
    ERROR_CREATEDIR = -6,
    ERROR_UNKNOWN = -999,
  }
}
